version: "3"

vars:
  WSL_DISTRO: Debian
  WSL_USER: cb
  WSL_DRIVE_PATH: "E:/wsl"
  BACKUP_PATH: "E:/backups"
  REPO_URL: "https://github.com/cbalona/dotfiles.git"

tasks:
  default:
    desc: "Full System Setup"
    cmds:
      - task: setup-windows-git
      - task: powertoys-restore
      - task: wsl-move-drive
      - task: wsl-configure

  setup-windows-git:
    desc: "Links Windows Git config to the dotfiles repo"
    platforms: [windows]
    vars:
      USER_HOME: "{{.USERPROFILE}}"
      REPO_CONFIG: '{{.USER_WORKING_DIR}}\configs\gitconfig'
    cmds:
      # Remove existing .gitconfig if it's a file (backup if needed)
      - powershell -Command "if (Test-Path '{{.USER_HOME}}\.gitconfig') { Remove-Item '{{.USER_HOME}}\.gitconfig' }"

      # Create Link
      - powershell -Command "New-Item -ItemType SymbolicLink -Path '{{.USER_HOME}}\.gitconfig' -Target '{{.REPO_CONFIG}}'"
      - powershell -Command "Set-Content -Path '{{.USER_HOME}}\.gitconfig.local' -Value '[credential]`r`n    helper = manager'"

      - echo "Windows Git Config Linked."

  powertoys-backup:
    desc: "Backs up PowerToys settings to the dotfiles repo"
    platforms: [windows]
    vars:
      POWTOYS_CONFIG_SRC: '{{.USERPROFILE}}\AppData\Local\Microsoft\PowerToys'
      POWTOYS_CONFIG_DEST: '{{.USER_WORKING_DIR}}\configs\powertoys'
    cmds:
      - |
        powershell -Command "
          if (-not (Test-Path '{{.POWTOYS_CONFIG_DEST}}')) {
            New-Item -ItemType Directory -Path '{{.POWTOYS_CONFIG_DEST}}' | Out-Null
          }
          Write-Host 'Backing up PowerToys settings...'
          Copy-Item -Path '{{.POWTOYS_CONFIG_SRC}}\settings.json' -Destination '{{.POWTOYS_CONFIG_DEST}}' -Force
        "
      - echo "PowerToys backup complete."

  powertoys-restore:
    desc: "Restores PowerToys settings from the dotfiles repo"
    platforms: [windows]
    vars:
      POWTOYS_CONFIG_SRC: '{{.USER_WORKING_DIR}}\configs\powertoys'
      POWTOYS_CONFIG_DEST: '{{.USERPROFILE}}\AppData\Local\Microsoft\PowerToys'
    cmds:
      - |
        powershell -NoProfile -Command "
          if (-not (Test-Path '{{.POWTOYS_CONFIG_SRC}}')) {
            Write-Warning 'PowerToys config not found in dotfiles. Skipping restore.'
            exit 0
          }
          Write-Host 'Restoring PowerToys settings...'
          Stop-Process -Name 'PowerToys.Runner' -ErrorAction SilentlyContinue
          Copy-Item -Path '{{.POWTOYS_CONFIG_SRC}}\*.json' -Destination '{{.POWTOYS_CONFIG_DEST}}' -Force
          Start-Process -FilePath 'C:\Program Files\PowerToys\PowerToys.exe'
        "
      - echo "PowerToys restore complete."

  wsl-move-drive:
    desc: "Moves WSL execution to the target drive"
    platforms: [windows]
    status:
      - powershell -NoProfile -Command "if (Test-Path '{{.WSL_DRIVE_PATH}}/{{.WSL_DISTRO}}') { exit 0 } else { exit 1 }"
    cmds:
      - echo "Moving {{.WSL_DISTRO}} to {{.WSL_DRIVE_PATH}}..."
      - wsl --shutdown
      - mkdir {{.WSL_DRIVE_PATH}}
      - mkdir {{.BACKUP_PATH}}
      - wsl --export {{.WSL_DISTRO}} {{.BACKUP_PATH}}/temp_distro.tar
      # Verify export size
      - powershell -Command "if ((Get-Item '{{.BACKUP_PATH}}/temp_distro.tar').Length -lt 1000000) { Write-Error 'Export failed/too small'; exit 1 }"
      - wsl --unregister {{.WSL_DISTRO}}
      - wsl --import {{.WSL_DISTRO}} {{.WSL_DRIVE_PATH}}/{{.WSL_DISTRO}} {{.BACKUP_PATH}}/temp_distro.tar
      - echo "WSL Moved successfully."
      - rm {{.BACKUP_PATH}}/temp_distro.tar
      - wsl -d {{.WSL_DISTRO}} bash -c "echo -e '[user]\ndefault={{.WSL_USER}}' | sudo tee /etc/wsl.conf"
      - wsl --terminate {{.WSL_DISTRO}}
      - echo "Move Complete. Restarting WSL..."

  wsl-configure:
    desc: "Bootstraps Linux and runs Ansible"
    status:
      - wsl -d {{.WSL_DISTRO}} bash -c "if [ -d ~/dotfiles ]; then exit 0; else exit 1; fi"
    cmds:
      - wsl -d {{.WSL_DISTRO}} bash -c "command -v git >/dev/null || (sudo apt update && sudo apt install -y git)"
      - wsl -d {{.WSL_DISTRO}} bash -c "if [ ! -d ~/dotfiles ]; then git clone {{.REPO_URL}} ~/dotfiles; else cd ~/dotfiles && git pull; fi"
      - wsl -d {{.WSL_DISTRO}} bash -c "chmod +x ~/dotfiles/scripts/bootstrap.sh"
