version: '3'

vars:
  WSL_DISTRO: Debian
  WSL_USER: cb
  WSL_DRIVE_PATH: "E:/wsl"
  BACKUP_PATH: "E:/backups"
  REPO_URL: "https://github.com/cbalona/dotfiles.git"

tasks:
  default:
    desc: "Full System Setup"
    cmds:
      - task: setup-windows-git
      - task: wsl-move-drive
      - task: wsl-configure

  setup-windows-git:
    desc: "Links Windows Git config to the dotfiles repo"
    platforms: [windows]
    vars:
      USER_HOME: '{{.USERPROFILE}}'
      REPO_CONFIG: '{{.USER_WORKING_DIR}}\configs\gitconfig'
    cmds:
      # Remove existing .gitconfig if it's a file (backup if needed)
      - powershell -Command "if (Test-Path '{{.USER_HOME}}\.gitconfig') { Remove-Item '{{.USER_HOME}}\.gitconfig' }"
      
      # Create Link
      - powershell -Command "New-Item -ItemType SymbolicLink -Path '{{.USER_HOME}}\.gitconfig' -Target '{{.REPO_CONFIG}}'"
      
      - echo "Windows Git Config Linked."

  wsl-move-drive:
    desc: "Moves WSL execution to the target drive"
    platforms: [windows]
    status:
      - powershell -NoProfile -Command "if (Test-Path '{{.WSL_DRIVE_PATH}}/{{.WSL_DISTRO}}') { exit 0 } else { exit 1 }"
    cmds:
      - echo "Moving {{.WSL_DISTRO}} to {{.WSL_DRIVE_PATH}}..."
      - wsl --shutdown
      - mkdir {{.WSL_DRIVE_PATH}}
      - mkdir {{.BACKUP_PATH}}
      - wsl --export {{.WSL_DISTRO}} {{.BACKUP_PATH}}/temp_distro.tar
      - wsl --unregister {{.WSL_DISTRO}}
      - wsl --import {{.WSL_DISTRO}} {{.WSL_DRIVE_PATH}}/{{.WSL_DISTRO}} {{.BACKUP_PATH}}/temp_distro.tar
      - echo "WSL Moved successfully."
      - rm {{.BACKUP_PATH}}/temp_distro.tar
      - wsl -d {{.WSL_DISTRO}} bash -c "echo -e '[user]\ndefault={{.WSL_USER}}' | sudo tee /etc/wsl.conf"
      - wsl --terminate {{.WSL_DISTRO}}
      - echo "Move Complete. Restarting WSL..."

  wsl-configure:
    desc: "Bootstraps Linux and runs Ansible"
    status:
      - wsl -d {{.WSL_DISTRO}} bash -c "if [ -d ~/dotfiles ]; then exit 0; else exit 1; fi"
    cmds:
      - wsl -d {{.WSL_DISTRO}} bash -c "command -v git >/dev/null || (sudo apt update && sudo apt install -y git)"
      - wsl -d {{.WSL_DISTRO}} bash -c "if [ ! -d ~/dotfiles ]; then git clone {{.REPO_URL}} ~/dotfiles; else cd ~/dotfiles && git pull; fi"
      - wsl -d {{.WSL_DISTRO}} bash -c "chmod +x ~/dotfiles/scripts/bootstrap.sh"