# PATHS & ENV
export EDITOR='code --wait'
# Ensure local bin is prioritised for tools like uv/rust
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH" 

# ZSH OPTIONS
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# INIT STARSHIP
eval "$(starship init zsh)"

# BAT
if command -v batcat > /dev/null; then
  alias bat='batcat'
fi
alias cat='bat --style=plain'

# NALA
alias apt='sudo nala'
alias install='sudo nala install'
alias update='sudo nala update && sudo nala upgrade'

# EZA
alias ls='eza --icons --git --group-directories-first'
alias ll='eza -al --icons --git --group-directories-first'
alias lt='eza -alT --icons --git-ignore --level=2'

# ZOXIDE
alias cd='z'
eval "$(zoxide init zsh)"

# FZF
source <(fzf --zsh)

# PLUGINS
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# CODE2PROMPT
alias c2p='code2prompt -c'
